# Generated by Django 2.2.2 on 2020-12-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20201230_1016"),
    ]

    operations = [
        migrations.RemoveField(model_name="emailuseraddress", name="state",),
        migrations.RemoveField(model_name="emailuseraddress", name="user",),
        migrations.DeleteModel(name="BankAccount",),
        migrations.DeleteModel(name="EmailUserAddress",),
        migrations.DeleteModel(name="State",),
    ]
