# Generated by Django 3.1.4 on 2020-12-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201230_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
