# Generated by Django 3.1.4 on 2021-01-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20210102_0940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordtoken",
            name="category",
            field=models.CharField(
                choices=[("signup", "signup"), ("reset", "reset")],
                default="signup",
                max_length=6,
            ),
        ),
    ]
