# Generated by Django 3.1.4 on 2021-01-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210102_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('owner', 'owner'), ('employee', 'employee')], default='employee', max_length=8),
        ),
    ]
