# Generated by Django 3.1.4 on 2021-02-03 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20210102_1614"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MobileToken",
        ),
    ]
