# Generated by Django 3.1.4 on 2021-02-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_mobiletoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletoken',
            name='verified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordtoken',
            name='verified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
