# Generated by Django 3.1.4 on 2021-02-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210203_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobiletoken',
            old_name='verified_time',
            new_name='used_time',
        ),
        migrations.RenameField(
            model_name='passwordtoken',
            old_name='verified_time',
            new_name='used_time',
        ),
    ]
