# Generated by Django 3.1.4 on 2022-05-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderoption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderOption',
            new_name='JobType',
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'verbose_name': 'Job Type', 'verbose_name_plural': 'Job Types'},
        ),
    ]
