# Generated by Django 2.2.2 on 2020-12-30 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("gstin", models.CharField(max_length=15)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("laboratory", "laboratory"),
                            ("dentist", "dentist"),
                            ("accountant", "accountant"),
                        ],
                        default="laboratory",
                        max_length=12,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business",
                "verbose_name_plural": "Businesses",
            },
        ),
        migrations.CreateModel(
            name="BusinessContact",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact", models.CharField(max_length=255)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("mobile", "mobile"),
                            ("landline", "landline"),
                            ("email", "email"),
                        ],
                        default="mobile",
                        max_length=255,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="businesses.Business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Contact",
                "verbose_name_plural": "Business Contacts",
            },
        ),
        migrations.CreateModel(
            name="BusinessAddress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=255)),
                ("pincode", models.CharField(max_length=6)),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("headquarters", "headquarters"),
                            ("branch", "branch"),
                        ],
                        default="headquarters",
                        max_length=8,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="businesses.Business",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="addresses",
                        to="core.State",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Address",
                "verbose_name_plural": "Business Addresses",
                "ordering": ["business", "address_type"],
            },
        ),
        migrations.CreateModel(
            name="BusinessAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
                ("ifsc_code", models.CharField(max_length=11)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("current", "current"), ("savings", "savings")],
                        default="current",
                        max_length=255,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="businesses.Business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Account",
                "verbose_name_plural": "Business Accounts",
            },
        ),
    ]
