# Generated by Django 3.1.4 on 2022-05-10 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('businesses', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='from_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_created', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='order',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='job_types',
            field=models.ManyToManyField(related_name='orders', to='core.JobType'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_received', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='order',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessowner',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_owners', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessowner',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_business', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessemployee',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessemployee',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesscontact',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessconnect',
            name='from_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentists', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessconnect',
            name='to_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='core.city'),
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='core.district'),
        ),
        migrations.AddField(
            model_name='businessaddress',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='core.state'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='businesses.business'),
        ),
        migrations.AddField(
            model_name='business',
            name='connected_businesses',
            field=models.ManyToManyField(blank=True, related_name='conencted_business', through='businesses.BusinessConnect', to='businesses.Business'),
        ),
        migrations.AddField(
            model_name='business',
            name='owners',
            field=models.ManyToManyField(blank=True, through='businesses.BusinessOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='business',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='businesses.business'),
        ),
    ]
