# Generated by Django 3.1.4 on 2021-01-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_auto_20201230_1638"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessaccount",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="businessaddress",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
