# Generated by Django 3.1.4 on 2022-05-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_auto_20220510_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='connected_businesses',
            field=models.ManyToManyField(blank=True, related_name='_business_connected_businesses_+', through='businesses.BusinessConnect', to='businesses.Business'),
        ),
    ]
