# Generated by Django 3.1.4 on 2021-01-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_auto_20210101_1642"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="latest_status",
            field=models.CharField(
                choices=[
                    ("suspended", "suspended"),
                    ("pending", "pending"),
                    ("completed", "completed"),
                    ("delivered", "delivered"),
                    ("rework", "rework"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("suspended", "suspended"),
                    ("pending", "pending"),
                    ("completed", "completed"),
                    ("delivered", "delivered"),
                    ("rework", "rework"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
