# Generated by Django 3.1.4 on 2021-01-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0005_auto_20210102_1136"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
