# Generated by Django 3.1.4 on 2021-01-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0006_business_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="latest_status",
            field=models.CharField(
                choices=[
                    ("suspended", "suspended"),
                    ("pending", "pending"),
                    ("working", "working"),
                    ("completed", "completed"),
                    ("delivered", "delivered"),
                    ("rework", "rework"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatus",
            name="status",
            field=models.CharField(
                choices=[
                    ("suspended", "suspended"),
                    ("pending", "pending"),
                    ("working", "working"),
                    ("completed", "completed"),
                    ("delivered", "delivered"),
                    ("rework", "rework"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
