# Generated by Django 3.1.4 on 2021-02-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_auto_20210122_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessEmployee',
        ),
    ]
