# Generated by Django 3.1.4 on 2021-02-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0009_businessemployee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="gstin",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
