# Generated by Django 3.1.4 on 2021-02-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0010_auto_20210204_0904"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesscontact",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
