# Generated by Django 3.1.4 on 2021-07-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0014_auto_20210722_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconnect',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
