# Generated by Django 3.1.4 on 2021-08-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0015_businessconnect_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessaccount',
            name='account_number',
            field=models.IntegerField(),
        ),
    ]
