# Generated by Django 3.1.4 on 2021-08-04 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0017_auto_20210804_0445"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="from_business",
            new_name="from_dentist",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="to_business",
            new_name="to_laboratory",
        ),
    ]
