# Generated by Django 3.1.4 on 2021-09-17 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("businesses", "0019_auto_20210804_0630"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="owner",
        ),
        migrations.AlterField(
            model_name="business",
            name="connected_businesses",
            field=models.ManyToManyField(
                blank=True,
                related_name="conencted_business",
                through="businesses.BusinessConnect",
                to="businesses.Business",
            ),
        ),
        migrations.CreateModel(
            name="BusinessOwner",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_owners",
                        to="businesses.business",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_business",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Owner",
                "verbose_name_plural": "Business Owners",
            },
        ),
        migrations.AddField(
            model_name="business",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                through="businesses.BusinessOwner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
