# Generated by Django 3.1.4 on 2021-10-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0020_auto_20210917_1426"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
