# Generated by Django 3.1.4 on 2022-02-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0021_business_website"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="from_dentist",
            new_name="from_business",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="to_laboratory",
            new_name="to_business",
        ),
    ]
