# Generated by Django 3.1.4 on 2022-05-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0024_business_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="is_claimed",
            field=models.BooleanField(default=True),
        ),
    ]
