# Generated by Django 3.1.4 on 2022-05-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0025_business_is_claimed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='options',
        ),
    ]
