# Generated by Django 3.1.4 on 2022-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220508_1839'),
        ('businesses', '0026_remove_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='job_types',
            field=models.ManyToManyField(related_name='orders', to='core.JobType'),
        ),
    ]
